### ISSUE TITLE
island1 Screen Huaping （fceux2.6.1）

### ISSUE THREAD

**Issue by kongmao45678** [TASEmulators/fceux#453]
![QQ截图20220128090114](https://user-images.githubusercontent.com/79181884/151468788-05e820c8-fcfc-4dcc-a3b0-cc33a84f4d0e.png)
![QQ截图20220128090121](https://user-images.githubusercontent.com/79181884/151468791-58f1b451-492c-434d-90d6-51908a6e5537.png)

**Comment by mjbudd77** [comment]
This issue report does not follow the template. Lots of missing details here. Please provide how to reproduce issue. I downloaded what I think this ROM is and it ran without issues.

**Comment by mjbudd77** [comment]
Please recheck this on latest. It may have been fixed by recent changes.

**Comment by kongmao45678** [comment]
[冒险岛1.zip](https://github.com/TASEmulators/fceux/files/8031428/1.zip)
Please use this ROM for testing, I just used the latest 2.6.2 and still have this error. Used the MESEN test and it was good.
