### ISSUE TITLE
Transparent main screen when running

### ISSUE THREAD

**Issue by sensha** [TASEmulators/fceux#513]
When FCEUX is opened under Fedora 36/GNOME 42 with OpenGL the main screen area of the app is transparent. Using SDL does not fix it and just shows a black screen instead of the game instead.
See screenshots below, they show part of my wallpaper and some window title bars that would normally be behind the fceux window when it is focused.

This also affects when a game is playing (see screenshots) the game itself becomes semi-transparent.

**To Reproduce**
1. Install FCEUX either via Fedora repo or compiling direct from github
2. Open FCEUX

**Expected behavior**
The main screen area would usually be black before you load a game.

**Screenshots**
![fceux_bug2](https://user-images.githubusercontent.com/18188159/169795825-dbc7e99c-d031-435e-ab3f-e099d4b519fe.png)
![fceux_bug1](https://user-images.githubusercontent.com/18188159/169795918-71889c67-2abd-481b-afff-f57c30cc63ac.png)

**(please complete the following information):**
 - OS and Version: Fedora 36, also tested on Fedora 35
 - Kernel 5.17.8
 - NVIDIA Drivers 510.68.02
 - QT version - FCEUX version 2.6.4 and current github build (both have the same bug)

Console output:
```
Qt Warning: QSocketNotifier: Can only be used with threads started with QThread (:0, )
Qt Warning: QSocketNotifier: Can only be used with threads started with QThread (:0, )
Starting FCEUX 2.6.4...
PAL mode set
PAL mode set
Running on Platform: wayland
Emulator Start
GL Version: 4.6.0 NVIDIA 510.68.02 
```

**Comment by mjbudd77** [comment]
I believe others have also seen this issue as it was reported in #381 . Try changing gnome to use x11 instead of wayland.

**Comment by Amnesia1000** [comment]
Is it possible to use fceux from a wayland session? Without having to login to x11?

**Comment by zeromus** [comment]
so is this fixed now? @thor2016  ?

**Comment by thor2016** [comment]
@zeromus the changes I made in the PR mentioned above fixed this issue for me. I have a similar setup as @sensha. I think this should fix it for all linux wayland users. That said, I shouldn't have had to do what I did to make it work (turning on GL_BLEND function with blend controls set to no blending). But it works and I haven't seen any difference in performance or issues when switching back to X11. Maybe have the others interested in this issue try out the fix by compiling from the latest in git? I should also say that my fix is only for the OpenGL driver in the Qt GUI. The SDL driver fails because of a known Qt issue with the function QWidget::winId() when using linux wayland. The SDL driver needs to be able to obtain a window ID through the use of that function, without it is unusable. The Qt issue can be referenced here: https://bugreports.qt.io/browse/QTBUG-76983

**Comment by zeromus** [comment]
lets just guess it's fixed

**Comment by ReillyBrogan** [comment]
Can we re-open this issue? I just updated the Solus package to 2.6.5 (which according to the git log contains the transparency fixes) and this is still happening on Plasma Wayland (5.27.4). I tested in x11 and it works as expected there.

**Comment by thor2016** [comment]
I've made further changes. Can someone build and test from the latest source? I have not been able to repro on Ubuntu.

**Comment by thor2016** [comment]
I was finally able to repro the issue on Fedora 36 running in a VM. I was able to verify my fix for both the OpenGL and QPainter drivers. SDL driver is not going to work on wayland due to known issue with Qt winId function. I will take 2 out of 3 as a win and call this fixed since the SDL video issue is out of my control.
